### ISSUE TITLE
FatTreeTopo has no attribute node_info

### ISSUE THREAD

**Issue by gbala88** [brandonheller/ripl#2]
I am not sure if this repository is still maintained, but there was this error in the dctopo.py file. It is with respect to FatTreeTopo class referring to a non-existent node_info variable in the layer function.

**Comment by HelloChristie** [comment]
hi 
were you able to solve it ?

**Comment by Horkyze** [comment]
Im also getting the same error

```
AttributeError: 'FatTreeTopo' object has no attribute 'node_info'
ERROR:core:Exception while handling OpenFlowNexus!PacketIn...
Traceback (most recent call last):
  File "/root/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/root/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/root/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "build/bdist.linux-x86_64/egg/riplpox/riplpox.py", line 344, in _handle_PacketIn
    self._handle_packet_reactive(event)
  File "build/bdist.linux-x86_64/egg/riplpox/riplpox.py", line 246, in _handle_packet_reactive
    self._flood(event)
  File "build/bdist.linux-x86_64/egg/riplpox/riplpox.py", line 206, in _flood
    for sw in self._raw_dpids(t.layer_nodes(t.LAYER_EDGE)):
  File "build/bdist.linux-x86_64/egg/ripl/dctopo.py", line 135, in layer_nodes
    nodes = [n for n in self.g.nodes() if is_layer(n)]
  File "build/bdist.linux-x86_64/egg/ripl/dctopo.py", line 133, in is_layer
    return self.layer(n) == layer
  File "build/bdist.linux-x86_64/egg/ripl/dctopo.py", line 115, in layer
    return self.node_info[name]['layer']
```

@brandonheller any ideas?

**Comment by shwethabetageri** [comment]
got solution for
this

def layer(self, name):
        '''Return layer of a node""

     
        return self.g.node[name]['layer']
        #return self.node_info[name]['layer']
